// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTonHYD2--gid8jHAULknjkB_WTS_7va8',
    appId: '1:1082920654128:web:d5a94fb9fdbe1ae0af24f5',
    messagingSenderId: '1082920654128',
    projectId: 'chamsocpet-35e6f',
    authDomain: 'chamsocpet-35e6f.firebaseapp.com',
    storageBucket: 'chamsocpet-35e6f.firebasestorage.app',
    measurementId: 'G-2VNEF2N110',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXwmA4cB1EG8CbzbgcKRvf7uUCNueFmQE',
    appId: '1:1082920654128:android:d24ac3b88683b773af24f5',
    messagingSenderId: '1082920654128',
    projectId: 'chamsocpet-35e6f',
    storageBucket: 'chamsocpet-35e6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm8qF7Ud_YDowSs1XaR1uTRkEeSRerz0w',
    appId: '1:1082920654128:ios:4d16776da2c79661af24f5',
    messagingSenderId: '1082920654128',
    projectId: 'chamsocpet-35e6f',
    storageBucket: 'chamsocpet-35e6f.firebasestorage.app',
    iosBundleId: 'com.example.chamsocpet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm8qF7Ud_YDowSs1XaR1uTRkEeSRerz0w',
    appId: '1:1082920654128:ios:4d16776da2c79661af24f5',
    messagingSenderId: '1082920654128',
    projectId: 'chamsocpet-35e6f',
    storageBucket: 'chamsocpet-35e6f.firebasestorage.app',
    iosBundleId: 'com.example.chamsocpet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTonHYD2--gid8jHAULknjkB_WTS_7va8',
    appId: '1:1082920654128:web:694d92ea718ecfb9af24f5',
    messagingSenderId: '1082920654128',
    projectId: 'chamsocpet-35e6f',
    authDomain: 'chamsocpet-35e6f.firebaseapp.com',
    storageBucket: 'chamsocpet-35e6f.firebasestorage.app',
    measurementId: 'G-DTF9RVTKLJ',
  );
}
